### PR TITLE
Implicit 'projectPath' for Broccoli Plugin

### PR DESCRIPTION
**Pull request by chadhietala**
This makes the broccoli plugin actually usable within an ember-cli project. Prior to this commit we assuming passing an entire project root into the plugin however in practice just the `src` directory will be used. This moves to an implicit assumption that the `inputPath` is the root of the project. This means the tree that is passed to the plugin must contain the package.json.

### CODE REVIEW

**Comment by rwjblue** [comment]
Not sure how this wouldn’t cause recursive rebuilds on systems without watchman because the project `tmp` would be inside this root tree being passed in, and change events in `./tmp` would trigger a rebuild.

What am I missing here?

**Comment by rwjblue** [comment]
So you are saying we would clone the package.json into an unwatched tree, funnel `src` (as a watched tree), then merge the two together? In other words, we would _not_ be passing in the project root as the root tree, we would just be making it _seem_ like that’s what we are doing?

**Comment by chadhietala** [comment]
@rwjblue Correct. @tomdale Likely can talk more about why the `package.json` needs to be there at all.

**Comment by tomdale** [comment]
The `package.json` is needed to infer the module prefix name.

**Pull request merged**
