### PR TITLE
Replace deprecated `qunitjs` dependency with `qunit`

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/qunitjs/qunit/pull/1232

### CODE REVIEW

**Comment by chadhietala** [comment]
This created more type errors since the typedefs are not updated.

**Comment by rwjblue** [comment]
Why do type errors not fail the build?

**Comment by Turbo87** [comment]
> This created more type errors since the typedefs are not updated.

where are the typedefs?

**Comment by rwjblue** [comment]
@Turbo87 - Presumably `@types/qunit`?
 
https://github.com/glimmerjs/glimmer.js/blob/master/package.json#L18

**Comment by rwjblue** [comment]
But it doesn't seem like https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/qunit/index.d.ts actually indicates the package that you are requiring/importing from, so I'm unsure what @chadhietala is referring to then...

**Pull request merged**
