### PR TITLE
[wip] partially fix 'Turn on `noImplicitAny` #56'

### PR DESCRIPTION
**Pull request by c0urg3tt3**
i try to use appropriate type when possible, but i mostly use `any` when i'm not sure because it can easily been searched to see what kind of type are really needed later, or while solving this PR.

note: i doesn't touch at `app-compiler/src/bundle-compiler.ts` as @topaxi as submitted a [PR](https://github.com/glimmerjs/glimmer.js/pull/58) relative to this file

### CODE REVIEW

**Comment by rwjblue** [comment]
@tomdale  - Would you mind starting some initial rounds of review here?

**Comment by tomdale** [comment]
@c0urg3tt3 Thanks for the PR! A couple notes on this:

1. We prefer the `value as Type` casting syntax to the `<Type>value` syntax, as it seems that's the direction the TS team is pushing folks.
2. Generally speaking, I'd prefer to avoid *explicit* `any` as well as implicit `any`. There are some instances where `any` is correct or acceptable (e.g. in tests where properly typing stub objects would be annoying without much value). But there are several instances in this PR where it should be possible to use the proper types. If it's not obvious what they are (which is totally understandable!) maybe we can stick to "real" `any` and other scalar types like `string`, `number` etc for now?

**Comment by c0urg3tt3** [comment]
@tomdale thank you for the advices, i'll try to enhance the PR !

**Comment by pzuraq** [comment]
This has been enabled on master. Thank you for your efforts!

**Pull request closed without merging**
